scripts:
    # ....
  - name: Install npm dependencies
    script: |
      npm install
  - name: Set Android SDK location
    script: |
      echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
  - name: Build Android release
    script: |
      cd android
      ./gradlew bundleRelease

artifacts:
  - android/app/build/outputs/**/*.aab